### ISSUE TITLE
`hexcolor` does not specify a Swift version 

### ISSUE THREAD

**Issue by rohitBhujbal** [ggichure/hexcolor#1]
Getting following error while building a XCFramework from flutter module.

**[!] Unable to determine Swift version for the following pods:

- `hexcolor` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.**

**Comment by ggichure** [comment]
hey ,i'm looking into this ,should get back to you soon

**Comment by ggichure** [comment]
this has been fixed in this commit https://github.com/ggichure/hexcolor/commit/5b49b10e36e964586476ba9571fa6ca8608cb2d3

**Comment by JAYTARPARA** [comment]
Issue is still occurring in latest version
![WhatsApp Image 2021-03-01 at 12 43 21 PM](https://user-images.githubusercontent.com/11882157/109466524-d822bf80-7a8f-11eb-8abf-ec781586ed20.jpeg)
