### ISSUE TITLE
hexcolor-swift.h header not found

### ISSUE THREAD

**Issue by darmie** [ggichure/hexcolor#2]
I am having this error:

```
HexcolorPlugin.m:2:9: fatal error: 'hexcolor/hexcolor-Swift.h' file not found
    #import <hexcolor/hexcolor-Swift.h>
```

**Comment by ggichure** [comment]
this has been fixed in this commit 5b49b10

**Comment by JAYTARPARA** [comment]
Issue is still occurring in latest version

![WhatsApp Image 2021-03-01 at 12 43 21 PM](https://user-images.githubusercontent.com/11882157/109466429-b4f81000-7a8f-11eb-9071-a4b6079ec808.jpeg)

**Comment by NusLookingForYou** [comment]
I have the same problem

**Comment by NusLookingForYou** [comment]
You can fill in "use_frameworks!" in "Podfile."
 good luck

**Comment by aidencrilley** [comment]
I am still struggling with this issue, and have not found a fix yet.

**Comment by ggichure** [comment]
Please use version 3.0.0 and above, The package is now a dart package. no ios or android deps.
